# Generated by Django 2.2 on 2023-12-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fabricante',
            field=models.CharField(choices=[('CAT', 'Caterpillar'), ('KMT', 'Komatsu'), ('X', 'XCMG'), ('JD', 'John Deere'), ('S', 'Sany')], default=('KMT', 'Komatsu'), max_length=3),
        ),
    ]
