# Generated by Django 2.2 on 2023-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fabricante',
            field=models.CharField(choices=[('CAT', 'Caterpillar'), ('KMT', 'Komatsu'), ('X', 'XCMG'), ('JD', 'John Deere'), ('S', 'Sany')], max_length=3),
        ),
    ]
