# Generated by Django 2.2 on 2023-12-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231203_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='order_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rental_duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='rental_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
    ]
