# Generated by Django 2.2 on 2023-12-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
