# Generated by Django 2.2 on 2023-12-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderitem_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
