# Generated by Django 2.2 on 2023-12-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20231206_1132'),
        ('core', '0002_opinion_item'),
    ]

    operations = [
    ]
